### ISSUE TITLE
Internship assignment issues

### ISSUE THREAD

**Issue by This-Is-Prince** [Lauquik/agri-api#1]
1. Project does not follow any convention.
2. Please read go-api-boot docs.
3. Please check this [Project](https://github.com/Kotlang/authGo) and follow conventions used in this Project.
4. go-api-boot support ODM by default, so please use that.

**Comment by Lauquik** [comment]
okay Understood @This-Is-Prince, I will restructure codebase and use convections, provided in the Authgo Project

**Comment by Lauquik** [comment]
@This-Is-Prince can you take a look please if, the new codebase structure and convections is okay, If need to change anything, let me know

**Comment by This-Is-Prince** [comment]
Hey @Lauquik , I've gone through the updated codebase and it's looking good — all the issues I pointed out have been tackled. Great job on that! The team will reach out to you soon.
